baseURL = "https://example.com/"
languageCode = "en-us"
title = "Blog"
theme = "lekh"

[params]
Name = "d4sein"
About = "No description. Yet."
Email = "info@d4sein.dev"
Resume = "" # Add the filename with file extension.
PostLimit = 5 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/d4sein"

[[params.profiles]]
name = "Goodreads"
url = "https://www.goodreads.com/user/show/134591540-willian"

[[params.profiles]]
name = "LinkedIn"
url = ""